world: world
blue:
  x: 1
  y: 1
  z: 1
  ranks:
    private:
    corporal:
    sergeant:
    general:
      - Flamo_Z
red:
  x: 1
  y: 1
  z: 1
  ranks:
    private:
    corporal:
      - einkelflugle
    sergeant:
    general:
